# Generated by Django 3.2.16 on 2022-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sourav', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
